# Generated by Django 3.1.1 on 2020-10-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnioCursado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(unique=True, verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
                'db_table': 'carreras_anios_cursado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(max_length=30, unique=True, verbose_name='Nombre Corto')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('plan', models.CharField(blank=True, max_length=20, null=True, verbose_name='Plan de Estudios')),
                ('duracion', models.IntegerField(verbose_name='Duración')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'carreras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoCursado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'db_table': 'carreras_periodos_cursado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TiposCarreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'carreras_tipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
                ('nombre_corto', models.CharField(max_length=30, unique=True, verbose_name='Nombre Corto')),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.aniocursado', verbose_name='Año')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.carreras', verbose_name='Carrera')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.periodocursado', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'materias',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='carreras',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.tiposcarreras', verbose_name='Tipo'),
        ),
    ]
