# Generated by Django 3.1.1 on 2020-10-01 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucional', '0004_auto_20200930_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposCarreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'carreras_tipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=5, unique=True, verbose_name='Carrera')),
                ('nombre_corto', models.CharField(max_length=30, unique=True, verbose_name='Nombre Corto')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('duracion', models.TextField(verbose_name='Duración')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institucional.facultad', verbose_name='Facultad')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.tiposcarreras', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'Carreras',
                'ordering': ['id'],
            },
        ),
    ]
