# Generated by Django 3.1.1 on 2020-10-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='nombre',
            field=models.TextField(verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='materias',
            name='nombre_corto',
            field=models.CharField(max_length=30, verbose_name='Nombre Corto'),
        ),
    ]
