# Generated by Django 3.1.1 on 2020-10-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_auto_20201005_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposComisiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'materias_tipos_comisiones',
                'ordering': ['id'],
            },
        ),
    ]
