# Generated by Django 3.1.1 on 2020-10-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_auto_20201001_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanesEstudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=5, unique=True, verbose_name='Carrera')),
                ('nombre', models.CharField(max_length=5, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Planes de Estudios',
                'db_table': 'carreras_planes',
                'ordering': ['id'],
            },
        ),
    ]
