# Generated by Django 3.1.1 on 2020-10-01 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_planesestudios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planesestudios',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.carreras', verbose_name='Carrera'),
        ),
    ]
