# Generated by Django 3.1.1 on 2020-10-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0004_auto_20201001_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planesestudios',
            name='nombre',
            field=models.CharField(max_length=5, verbose_name='Nombre'),
        ),
    ]
