# Generated by Django 3.1.1 on 2020-10-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0005_auto_20201001_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnioCursado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
                'db_table': 'carreras_anios_cursado',
                'ordering': ['id'],
            },
        ),
    ]
