# Generated by Django 3.1.1 on 2020-10-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0006_aniocursado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniocursado',
            name='anio',
            field=models.IntegerField(unique=True, verbose_name='Año'),
        ),
    ]
