# Generated by Django 3.1.1 on 2020-10-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0007_auto_20201001_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoCursado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.TextField(unique=True, verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'db_table': 'carreras_periodos_cursado',
                'ordering': ['id'],
            },
        ),
    ]
