# Generated by Django 3.1.1 on 2020-10-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0008_periodocursado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodocursado',
            old_name='periodo',
            new_name='nombre',
        ),
    ]
