# Generated by Django 3.1.1 on 2020-10-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0009_auto_20201001_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aniocursado',
            old_name='anio',
            new_name='nombre',
        ),
    ]
