# Generated by Django 3.1.1 on 2020-10-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salasvirtuales',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico Sala Virtual'),
        ),
    ]
