# Generated by Django 3.1.1 on 2020-11-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0002_auto_20201026_1819'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salasvirtuales',
            table='cuentas_salas_virtuales',
        ),
    ]
