# Generated by Django 3.1.1 on 2020-12-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0004_auto_20201119_1322'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salasvirtuales',
            table='plataformas_salas_virtuales',
        ),
    ]
