# Generated by Django 3.1.1 on 2020-12-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0005_auto_20201207_1640'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salasvirtuales',
            table='cuentas_salas_virtuales',
        ),
    ]
