# Generated by Django 3.1.1 on 2020-12-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0007_auto_20201207_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salasvirtuales',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='salasvirtuales',
            name='refresh_token',
        ),
    ]
