# Generated by Django 3.1.1 on 2020-10-06 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_tiposcomisiones'),
        ('institucional', '0001_initial'),
        ('solicitudes', '0002_solicitudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='apellido',
            field=models.TextField(default='1', verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='carrera',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.carreras', verbose_name='Carrera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='dni',
            field=models.PositiveIntegerField(default='1', verbose_name='DNI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='email',
            field=models.EmailField(default='aaa@aaa.com', max_length=254, verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='fecha_reserva',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='fin_hs',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='fin_repeticion',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='inicio_hs',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='materia',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.materias', verbose_name='Materia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='motivo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='solicitudes.motivos', verbose_name='Motivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='nombres',
            field=models.TextField(default='1', verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='repeticion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='sede',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='institucional.sedes', verbose_name='Sede'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='telefono',
            field=models.TextField(blank=True, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='tipo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='solicitudes.tiposolicitud', verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='nombre',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Solicitud'),
        ),
    ]
