# Generated by Django 3.1.1 on 2020-10-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_auto_20201006_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_reserva',
            field=models.DateField(verbose_name='Fecha de Reserva'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fin_hs',
            field=models.TimeField(verbose_name='Horario de Fin'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fin_repeticion',
            field=models.DateField(verbose_name='Fin de la Repetición'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='inicio_hs',
            field=models.TimeField(verbose_name='Horario de Inicio'),
        ),
    ]
