# Generated by Django 3.1.1 on 2020-10-06 21:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_tiposcomisiones'),
        ('solicitudes', '0004_auto_20201006_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='comision',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.tiposcomisiones', verbose_name='Tipo de Comisión'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_reserva',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Reserva'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fin_hs',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Horario de Fin'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fin_repeticion',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fin de la Repetición'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='inicio_hs',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Horario de Inicio'),
        ),
    ]
