# Generated by Django 3.1.1 on 2020-10-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_tiposcomisiones'),
        ('solicitudes', '0005_auto_20201006_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.carreras', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_reserva',
            field=models.DateField(verbose_name='Fecha de Reserva'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='fin_repeticion',
            field=models.DateField(verbose_name='Fin de la Repetición'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.materias', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solicitudes.tiposolicitud', verbose_name='Tipo de Reserva'),
        ),
    ]
