# Generated by Django 3.1.1 on 2020-10-08 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_tiposcomisiones'),
        ('solicitudes', '0007_auto_20201008_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='carrera',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.carreras', verbose_name='Carrera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='comision',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.tiposcomisiones', verbose_name='Tipo de Comisión'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='materia',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.materias', verbose_name='Materia'),
            preserve_default=False,
        ),
    ]
