# Generated by Django 3.1.1 on 2020-11-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0004_auto_20201119_1322'),
        ('solicitudes', '0008_auto_20201008_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservasVirtuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmacion_reserva', models.BooleanField(default=False)),
                ('id_cuenta_virtual', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataformas.salasvirtuales', verbose_name='id solicitud cuenta virtual')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solicitudes.solicitudes', verbose_name='id solicitud de reserva')),
            ],
            options={
                'verbose_name': 'reserva virtual',
                'verbose_name_plural': 'ResevervasVirtuales',
                'db_table': 'reservas_virtuales',
                'ordering': ['id'],
            },
        ),
    ]
