# Generated by Django 3.1.1 on 2020-12-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_reservasvirtuales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='fin_repeticion',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='repeticion',
        ),
    ]
