# Generated by Django 3.1.1 on 2020-12-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_auto_20201209_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservasvirtuales',
            options={'ordering': ['id'], 'verbose_name': 'reserva virtual', 'verbose_name_plural': 'ReservasVirtuales'},
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='estado',
            field=models.TextField(default='PENDIENTE', verbose_name='Estado'),
        ),
    ]
