# Generated by Django 3.1.1 on 2020-12-11 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_auto_20201211_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fin_hs',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario de Fin'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='inicio_hs',
            field=models.TimeField(verbose_name='Horario de Inicio'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='nombre',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Solicitud'),
        ),
    ]
