# Generated by Django 3.1.1 on 2020-12-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0016_auto_20201212_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='tipo',
        ),
    ]
