# Generated by Django 3.1.1 on 2020-12-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0017_remove_solicitudes_tipo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='solicitudes',
            table='reservas_salas_virtuales',
        ),
    ]
