# Generated by Django 3.0.4 on 2021-08-12 19:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucional', '0001_initial'),
        ('carreras', '0001_initial'),
        ('plataformas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivos',
                'db_table': 'solicitudes_motivos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'solicitudes_tipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Solicitud')),
                ('dni', models.PositiveIntegerField(verbose_name='DNI')),
                ('nombres', models.TextField(verbose_name='Nombres')),
                ('apellido', models.TextField(verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de Reserva')),
                ('inicio_hs', models.TimeField(verbose_name='Horario de Inicio')),
                ('fin_hs', models.TimeField(verbose_name='Horario de Fin')),
                ('estado', models.TextField(default='PENDIENTE', verbose_name='Estado')),
                ('link_reunion', models.TextField(blank=True, null=True, verbose_name='Link')),
                ('nombre_reunion', models.TextField(blank=True, null=True, verbose_name='Reunión')),
                ('password_reunion', models.TextField(blank=True, null=True, verbose_name='Contraseña')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.Carreras', verbose_name='Carrera')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.TiposComisiones', verbose_name='Tipo de Comisión')),
                ('cuenta_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plataformas.SalasVirtuales', verbose_name='Cuenta Asociada')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carreras.Materias', verbose_name='Materia')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solicitudes.Motivos', verbose_name='Motivo')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institucional.Sedes', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'reservas_salas_virtuales',
                'ordering': ['id'],
            },
        ),
    ]
