# Generated by Django 3.0.4 on 2021-08-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'paises',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.Paises', verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('codigo_postal', models.TextField(blank=True, null=True, verbose_name='Código Postal')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.Paises', verbose_name='Pais')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.Provincias', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidades',
                'ordering': ['id'],
            },
        ),
    ]
