# Generated by Django 3.1.1 on 2020-09-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultad',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='sedes',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='universidad',
            name='localidad',
        ),
    ]
