# Generated by Django 3.1.1 on 2020-10-01 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geografico', '__first__'),
        ('institucional', '0002_auto_20200930_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='localidad',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.localidades', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='sedes',
            name='localidad',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.localidades', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='universidad',
            name='localidad',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.localidades', verbose_name='Localidad'),
        ),
    ]
