# Generated by Django 3.1.1 on 2020-09-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='facultad',
        ),
    ]
