# Generated by Django 3.1.1 on 2020-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('apellido', models.TextField(verbose_name='Apellido')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('legajo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Legajo')),
                ('email', models.TextField(verbose_name='Correo Electrónico')),
                ('telefono', models.TextField(blank=True, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docentes',
                'ordering': ['id'],
            },
        ),
    ]
