# Generated by Django 3.1.1 on 2020-09-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuarios_facultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.TextField(blank=True, null=True),
        ),
    ]
