# Generated by Django 3.1.1 on 2020-10-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20201006_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='dni',
            field=models.PositiveIntegerField(max_length=8, unique=True, verbose_name='DNI'),
        ),
    ]
