# Generated by Django 3.1.1 on 2020-10-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20201006_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='dni',
            field=models.PositiveIntegerField(unique=True, verbose_name='DNI'),
        ),
    ]
