# Generated by Django 3.1.1 on 2020-10-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20201006_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='DNI'),
        ),
    ]
