# Generated by Django 3.1.1 on 2020-10-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
        ('usuarios', '0006_auto_20201006_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='sedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institucional.sedes', verbose_name='Sede'),
        ),
    ]
