# Generated by Django 3.1.1 on 2020-10-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuarios_sedes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='sedes',
            new_name='sede',
        ),
    ]
