# Generated by Django 3.1.1 on 2020-10-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20201006_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docentes',
            name='telefono',
        ),
    ]
