# Generated by Django 3.1.1 on 2020-12-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_docentes_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'usuarios_tipos',
                'ordering': ['id'],
            },
        ),
    ]
