# Generated by Django 3.1.1 on 2020-12-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_tiposusuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tiposusuarios', verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
