# Generated by Django 3.1.1 on 2020-12-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_usuarios_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Docentes',
        ),
    ]
