# Generated by Django 3.0.4 on 2021-08-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geografico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefonos', models.TextField(blank=True, null=True, verbose_name='Teléfonos')),
                ('web', models.TextField(blank=True, null=True, verbose_name='Página Web')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.Localidades', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Facultad',
                'db_table': 'facultad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefonos', models.TextField(blank=True, null=True, verbose_name='Teléfonos')),
                ('web', models.TextField(blank=True, null=True, verbose_name='Página Web')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.Localidades', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Universidad',
                'db_table': 'universidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefonos', models.TextField(blank=True, null=True, verbose_name='Teléfonos')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institucional.Facultad', verbose_name='Facultad')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.Localidades', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'sedes',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='facultad',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institucional.Universidad', verbose_name='Universidad'),
        ),
    ]
