# Generated by Django 3.1.1 on 2020-09-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('id_pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.paises')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('codigo_postal', models.IntegerField()),
                ('id_provincia', models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.provincias')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['nombre'],
            },
        ),
    ]
