# Generated by Django 3.1.1 on 2020-09-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultad',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='universidad',
            name='logo',
        ),
    ]
