# Generated by Django 3.1.1 on 2020-09-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geo.paises', verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincia',
                'db_table': 'provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('codigo_postal', models.IntegerField()),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geo.provincias', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidades',
                'ordering': ['nombre'],
            },
        ),
    ]
