# Generated by Django 3.1.1 on 2020-09-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidades',
            options={'ordering': ['id'], 'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='paises',
            options={'ordering': ['id'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='provincias',
            options={'ordering': ['id'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelTable(
            name='localidades',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paises',
            table=None,
        ),
        migrations.AlterModelTable(
            name='provincias',
            table=None,
        ),
    ]
