# Generated by Django 3.1.1 on 2020-09-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20200914_1630'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='localidades',
            table='localidades',
        ),
        migrations.AlterModelTable(
            name='paises',
            table='paises',
        ),
        migrations.AlterModelTable(
            name='provincias',
            table='provincias',
        ),
    ]
