# Generated by Django 3.1.1 on 2020-09-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20200914_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidades',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
