# Generated by Django 3.1.1 on 2020-09-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20200914_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidades',
            name='codigo_postal',
            field=models.TextField(blank=True, null=True, verbose_name='Provincia'),
        ),
    ]
