# Generated by Django 3.1.1 on 2020-09-14 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_auto_20200914_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidades',
            name='codigo_postal',
            field=models.TextField(blank=True, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='localidades',
            name='pais',
            field=models.ForeignKey(default='---------', on_delete=django.db.models.deletion.DO_NOTHING, to='geo.paises', verbose_name='Pais'),
        ),
    ]
