# Generated by Django 3.1.1 on 2020-09-14 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_auto_20200914_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidades',
            name='pais',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='geo.paises', verbose_name='Pais'),
        ),
    ]
