# Generated by Django 3.1.1 on 2020-09-14 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_auto_20200914_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidades',
            name='pais',
        ),
    ]
