# Generated by Django 3.1.1 on 2020-09-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0012_remove_localidades_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidades',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.paises', verbose_name='Pais'),
            preserve_default=False,
        ),
    ]
